import { DecimalPipe } from '@angular/common';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

export interface Product {
  id: number;
  image: string;
  name: string;
  price: number;
  availableNum: number;
  category: string;
}

export type Products = Product[];

@Injectable({
  providedIn: 'root',
})
export class Food {
  private mockProducts: Products = [
    {
      id: 1,
      image: 'assets/images/food1.png',
      name: 'Spicy seasoned seafood noodles',
      price: 2.29,
      availableNum: 20,
      category: 'hot dishes',
    },
    {
      id: 2,
      image: 'assets/images/food2.png',
      name: 'Salted Pasta with mushroom sauce',
      price: 2.69,
      availableNum: 11,
      category: 'hot dishes',
    },
    {
      id: 3,
      image: 'assets/images/food3.png',
      name: 'Beef dumpling in hot and sour soup',
      price: 2.99,
      availableNum: 16,
      category: 'hot dishes',
    },
    {
      id: 4,
      image: 'assets/images/food4.png',
      name: 'Healthy noodle with spinach leaf',
      price: 3.29,
      availableNum: 22,
      category: 'hot dishes',
    },
    {
      id: 5,
      image: 'assets/images/food4.png',
      name: 'Hot spicy fried rice with omelet',
      price: 3.49,
      availableNum: 13,
      category: 'hot dishes',
    },
    {
      id: 6,
      image: 'assets/images/food6.png',
      name: 'Spicy instant noodle with special omelette',
      price: 3.59,
      availableNum: 17,
      category: 'hot dishes',
    },
    {
      id: 7,
      image: 'assets/images/food2.png',
      name: 'Crispy fried chicken with garlic sauce',
      price: 3.79,
      availableNum: 14,
      category: 'hot dishes',
    },
    {
      id: 8,
      image: 'assets/images/food3.png',
      name: 'Stir fried vegetables with tofu',
      price: 2.99,
      availableNum: 18,
      category: 'hot dishes',
    },
    {
      id: 9,
      image: 'assets/images/food4.png',
      name: 'Braised pork belly with steamed buns',
      price: 4.29,
      availableNum: 9,
      category: 'hot dishes',
    },
    {
      id: 10,
      image: 'assets/images/food5.png',
      name: 'Cucumber salad with sesame dressing',
      price: 1.99,
      availableNum: 25,
      category: 'cold dishes',
    },
    {
      id: 11,
      image: 'assets/images/food1.png',
      name: 'Chilled tofu with spring onion',
      price: 1.79,
      availableNum: 30,
      category: 'cold dishes',
    },
    {
      id: 12,
      image: 'assets/images/food2.png',
      name: 'Cold sesame noodles with shredded chicken',
      price: 2.49,
      availableNum: 20,
      category: 'cold dishes',
    },
    {
      id: 13,
      image: 'assets/images/food3.png',
      name: 'Marinated jellyfish with vinegar',
      price: 2.29,
      availableNum: 15,
      category: 'cold dishes',
    },
    {
      id: 14,
      image: 'assets/images/food4.png',
      name: 'Smashed garlic eggplant salad',
      price: 1.89,
      availableNum: 22,
      category: 'cold dishes',
    },
    {
      id: 15,
      image: 'assets/images/food5.png',
      name: 'Spicy shredded pork ear salad',
      price: 2.59,
      availableNum: 12,
      category: 'cold dishes',
    },
    {
      id: 16,
      image: 'assets/images/food1.png',
      name: 'Cold poached chicken with chili oil',
      price: 2.99,
      availableNum: 18,
      category: 'cold dishes',
    },
    {
      id: 17,
      image: 'assets/images/food2.png',
      name: 'Pickled radish with sweet vinegar',
      price: 1.49,
      availableNum: 35,
      category: 'cold dishes',
    },
    {
      id: 18,
      image: 'assets/images/food3.png',
      name: 'Chilled lotus root with honey',
      price: 1.69,
      availableNum: 28,
      category: 'cold dishes',
    },
    {
      id: 19,
      image: 'assets/images/food4.png',
      name: 'Five spice beef shank slices',
      price: 3.29,
      availableNum: 10,
      category: 'cold dishes',
    },
    {
      id: 20,
      image: 'assets/images/food5.png',
      name: 'Cold spinach with peanut sauce',
      price: 1.59,
      availableNum: 32,
      category: 'cold dishes',
    },
    {
      id: 21,
      image: 'assets/images/food1.png',
      name: 'Soy marinated boiled eggs',
      price: 1.29,
      availableNum: 40,
      category: 'cold dishes',
    },
    {
      id: 22,
      image: 'assets/images/food2.png',
      name: 'Hot and sour soup with tofu',
      price: 2.19,
      availableNum: 24,
      category: 'soup',
    },
    {
      id: 23,
      image: 'assets/images/food3.png',
      name: 'Egg drop soup with tomato',
      price: 1.99,
      availableNum: 30,
      category: 'soup',
    },
    {
      id: 24,
      image: 'assets/images/food4.png',
      name: 'Wonton soup with pork filling',
      price: 2.79,
      availableNum: 18,
      category: 'soup',
    },
    {
      id: 25,
      image: 'assets/images/food5.png',
      name: 'Miso soup with seaweed and mushroom',
      price: 1.89,
      availableNum: 26,
      category: 'soup',
    },
    {
      id: 26,
      image: 'assets/images/food1.png',
      name: 'Spicy beef broth with glass noodles',
      price: 3.19,
      availableNum: 14,
      category: 'soup',
    },
    {
      id: 27,
      image: 'assets/images/food2.png',
      name: 'Pork bone broth with vegetables',
      price: 3.49,
      availableNum: 11,
      category: 'soup',
    },
    {
      id: 28,
      image: 'assets/images/food3.png',
      name: 'Creamy corn soup with chicken',
      price: 2.49,
      availableNum: 20,
      category: 'soup',
    },
    {
      id: 29,
      image: 'assets/images/food4.png',
      name: 'Mushroom and tofu clear broth',
      price: 2.09,
      availableNum: 22,
      category: 'soup',
    },
    {
      id: 30,
      image: 'assets/images/food5.png',
      name: 'Spicy lamb soup with herbs',
      price: 3.79,
      availableNum: 9,
      category: 'soup',
    },
    {
      id: 31,
      image: 'assets/images/food1.png',
      name: 'Seafood tofu soup with ginger',
      price: 3.29,
      availableNum: 13,
      category: 'soup',
    },
    {
      id: 32,
      image: 'assets/images/food2.png',
      name: 'Sweet corn and carrot soup',
      price: 1.79,
      availableNum: 28,
      category: 'soup',
    },
    {
      id: 33,
      image: 'assets/images/food3.png',
      name: 'Winter melon and pork rib soup',
      price: 2.89,
      availableNum: 16,
      category: 'soup',
    },
    {
      id: 34,
      image: 'assets/images/food4.png',
      name: 'Sour cabbage fish soup',
      price: 3.59,
      availableNum: 10,
      category: 'soup',
    },
    {
      id: 35,
      image: 'assets/images/food5.png',
      name: 'Lentil soup with cumin and lemon',
      price: 2.29,
      availableNum: 19,
      category: 'soup',
    },
    {
      id: 36,
      image: 'assets/images/food1.png',
      name: 'Chicken congee with ginger and scallion',
      price: 2.59,
      availableNum: 21,
      category: 'soup',
    },
  ];

  getProducts(): Observable<Products> {
    return of(this.mockProducts);
  }
}
